### ISSUE TITLE
Clean up examples

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ingest-graph-validator#1]
We have lots of tests here and example some of which are deprecated. Could we clean this up by removing some by simple deleting or adding to an archive folder is they may be useful in the future. 

Acceptance:

- [ ] remove any tests/examples that we don't need anymore
- [ ] add a note to the readme about which examples we should use.

**Comment by zperova** [comment]
@hewgreen Could you elaborate on `we don't need anymore` please?

**Comment by hewgreen** [comment]
Sure. I'm not sure what all these tests are. Could you add some information to the readme about what they are? At the moment only test5 works so I wondered if the others are needed. Also, I'm not sure what the uuid folders are. We may be able to delete these.

**Comment by javfg** [comment]
The example folder was cleaned up in the refactor. Two examples of a correct and defective 10x graph remain for testing purposes.
